#!/bin/bash
bash auto-publich-script "10-no_more_js" "find . -name '*.js' -type f -exec rm -f {} \;" "script that deletes all the regular files (not the directories) with a .js extension that are present in the current directory and all its subfolders."
