#!/bin/bash
bash auto-publich-script '11-binary_to_decimal' 'echo "$((2#$BINARY))"' 'script that converts a number from base 2 to base 10.  The number in base 2 is stored in the environment variable BINARY.'
