#!/bin/bash
bash auto-publich-script '8-true_knowledge' 'echo "$(($TRUEKNOWLEDGE + 128))\n"' 'script that prints the result of the addition of 128 with the value stored in the environment variable TRUEKNOWLEDGE, followed by a new line.'
